Profile view
vonfredd/projekt-grupp-2 pull request #55
Opened 2024-10-31 08:33 UTC by Emmelie83

Added a view for the profile view.

2024-10-31 10:19 UTC, vonfredd requested changes
Looks good,  we could add a guard to only allow users that are signed in to view the '/user' route. Since we save userData in localstorage we could check on that.

2024-10-31 10:19 UTC, vonfredd commented on frontend/src/router/index.js
> +        },
```suggestion
        {
            path: "/user",
            name: "userProfile",
            component: UserProfileView,
            beforeEnter: (to, from, next) => {
                if (localStorage.getItem('userData') !== null) {
                    next();
                } else {
                    alert('You need to sign in to see your profile')
                    next({ name: 'home' }); 
                }
            }
        },
```

2024-10-31 12:56 UTC, vonfredd approved these changes
Great! 🚀

2024-11-01 08:39 UTC, DevelopedByDanny approved these changes
Yes

2024-11-01 08:44 UTC, Mattan41 commented
logout button changes to login when viewing path /user. User is till logged in and can book seats to movies etc.

2024-11-01 08:50 UTC, merged